### ISSUE TITLE
Make the Venmo button testable from outside US contries

### ISSUE THREAD

**Issue by DanielePalombo** [solidusio/solidus_paypal_commerce_platform#137]
- [ ] Add `force_buyer_country` string [preference](https://github.com/solidusio-contrib/solidus_paypal_commerce_platform/blob/3a5f97d33c42f4123d737b58a46809de488b9090/app/models/solidus_paypal_commerce_platform/payment_method.rb#L6-L14) to PaymentMethod.
- [ ] If `force_buyer_country` is present, pass it as [buyer-country](https://developer.paypal.com/docs/business/javascript-sdk/javascript-sdk-configuration/#buyer-country) parameter to the [js SDK](https://github.com/solidusio-contrib/solidus_paypal_commerce_platform/blob/3a5f97d33c42f4123d737b58a46809de488b9090/app/models/solidus_paypal_commerce_platform/payment_method.rb#L67-L73)

**Comment by RyanofWoods** [comment]
Hi @DanielePalombo. Two questions:
1. Would it make more sense for `force_buyer_country` to be an `array` preference, so that the countries can be joined together appropriately? (I know we are only adding it for the value of `US` but perhaps for the future?) (I have never used `array` preferences however)
2. What do you think about a second check of `Rails.env`? As [PayPal says not to add](https://developer.paypal.com/docs/business/javascript-sdk/javascript-sdk-configuration/#buyer-country) the  `buyer-country` parameter in production.

**Comment by DanielePalombo** [comment]
1. I don't think it will allow an array. It's just the buyer_country, it should be just one.
2. Yes, Nice suggestion.

**Comment by RyanofWoods** [comment]
Ahh! I understand the `force_buyer_country` preference now. Thank you for your replies 🙂

**Comment by RyanofWoods** [comment]
This can be closed/resolved now @DanielePalombo
